name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies and build
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Test
        run: yarn test --ci --coverage
